force_flat: true

## Object-pallet pair
# Object params [dim_x, dim_y, dim_z]
large_box:
  - 0.53
  - 0.41
  - 0.21
small_box:
  - 0.447
  - 0.3
  - 0.08

# Pallet params -->
# For each pallet, the params are [tx, ty, tz, scx, scy, mx, my, pallet_length, pallet_width, pallet_height_limit, pallet_padding], where t_ for translation wrt robot base
# sc_ for start corner wrt pallet center when placing the boxes, m_ for margin between boxes
left_pallet:
  - 0.025
  - 1.01
  - 0.068
  - -1.0
  - 1.0
  - 0.02
  - 0.025
  - 1.025
  - 1.00
  - 1.0
  - -0.04

right_pallet:
  - 0.0
  - -1.00
  - 0.08
  - -1.0
  - -1.0
  - 0.015
  - 0.015
  - 0.91
  - 0.8
  - 1.0
  - -0.01


# Box bottom space when placing to pallet
z_spacing: 0.00

## Pick and place params [x, y, z] wrt robot base frame
pre_pick_offset:
  - 0.0
  - 0.0
  - 0.2
pre_place_offset:
  - 0.0
  - 0.0
  - 0.3

## Simulation only parameters
# Distance sensor param
void_range: 1.0

# If the centroid z value of the box is larger than this when it is on the conveyor,
# regard it as large box. The value is wrt robot base frame.
large_box_centroid_z: 1.02

## Real robot parameters
# Conveyor surface height wrt robot base frame mz_link0
conveyor_height: 0.95

# Parallel running parameters
detected_category: 0
detected_obj_pose_position: [0,0,0]
detected_obj_pose_orientation: [0,0,0,0]